# Cloudflare Pages Configuration
name = "auraa-luxury-store"
pages_build_output_dir = "frontend/build"

[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  cwd = ""
  watch_dir = "frontend"

[build.environment]
  NODE_VERSION = "18"

[env.production]
  vars = { }

