services:
  - type: web
    name: auraa-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGO_URL
        sync: false
      - key: MONGO_DB_NAME
        value: auraa_luxury_db
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CJ_API_KEY
        sync: false
      - key: CJ_DROPSHIP_API_KEY
        sync: false
      - key: CJ_DROPSHIP_EMAIL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: TURNSTILE_SECRET_KEY
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
