import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Supported languages with RTL detection
const LANGUAGES = {
  ar: { name: 'العربية', dir: 'rtl', flag: '🇸🇦' },
  en: { name: 'English', dir: 'ltr', flag: '🇬🇧' },
  fr: { name: 'Français', dir: 'ltr', flag: '🇫🇷' },
  es: { name: 'Español', dir: 'ltr', flag: '🇪🇸' },
  de: { name: 'Deutsch', dir: 'ltr', flag: '🇩🇪' },
  it: { name: 'Italiano', dir: 'ltr', flag: '🇮🇹' },
  tr: { name: 'Türkçe', dir: 'ltr', flag: '🇹🇷' },
  ur: { name: 'اردو', dir: 'rtl', flag: '🇵🇰' },
  hi: { name: 'हिन्दी', dir: 'ltr', flag: '🇮🇳' }
};

// GCC Currencies with proper decimal places
const CURRENCIES = {
  USD: { symbol: '$', decimals: 2, name_en: 'US Dollar', name_ar: 'دولار أمريكي' },
  SAR: { symbol: 'ر.س', decimals: 2, name_en: 'Saudi Riyal', name_ar: 'ريال سعودي' },
  AED: { symbol: 'د.إ', decimals: 2, name_en: 'UAE Dirham', name_ar: 'درهم إماراتي' },
  QAR: { symbol: 'ر.ق', decimals: 2, name_en: 'Qatari Riyal', name_ar: 'ريال قطري' },
  KWD: { symbol: 'د.ك', decimals: 3, name_en: 'Kuwaiti Dinar', name_ar: 'دينار كويتي' },
  BHD: { symbol: 'د.ب', decimals: 3, name_en: 'Bahraini Dinar', name_ar: 'دينار بحريني' },
  OMR: { symbol: 'ر.ع', decimals: 3, name_en: 'Omani Rial', name_ar: 'ريال عماني' }
};

const translations = {
  ar: {
    // Navigation
    home: 'الرئيسية',
    products: 'المنتجات',
    necklaces: 'قلادات',
    earrings: 'أقراط',
    rings: 'خواتم',
    bracelets: 'أساور',
    watches: 'ساعات',
    sets: 'أطقم',
    cart: 'السلة',
    profile: 'الملف الشخصي',
    admin: 'إدارة',
    login: 'دخول / تسجيل',
    logout: 'خروج',
    search_placeholder: 'ابحث عن المنتجات...',
    language: 'اللغة',
    
    // Homepage
    welcome_message: 'مرحباً بك في',
    hero_subtitle: 'اكتشف مجموعتنا الفاخرة من الاكسسوارات والمجوهرات الراقية',
    shop_now: 'تسوق الآن',
    featured_sets: 'الأطقم المميزة',
    free_shipping: 'شحن مجاني',
    free_shipping_desc: 'شحن مجاني لجميع الطلبات فوق 200 ريال',
    quality_guarantee: 'ضمان الجودة',
    quality_guarantee_desc: 'ضمان شامل على جميع منتجاتنا لمدة سنة كاملة',
    support_247: 'دعم 24/7',
    support_247_desc: 'فريق خدمة العملاء متاح على مدار الساعة',
    shop_by_category: 'تسوق حسب الفئة',
    featured_products: 'منتجات مميزة',
    newsletter_title: 'اشترك في نشرتنا الإخبارية',
    newsletter_subtitle: 'احصل على أحدث العروض والمنتجات الجديدة',
    subscribe: 'اشتراك',
    luxury_collection: 'مجموعة فاخرة',
    
    // Products
    all_products: 'جميع المنتجات',
    filter_results: 'تصفية النتائج',
    category: 'الفئة',
    all_categories: 'جميع الفئات',
    price_range: 'نطاق السعر',
    sort_by: 'ترتيب حسب',
    newest: 'الأحدث',
    price_low_high: 'السعر: من الأقل للأعلى',
    price_high_low: 'السعر: من الأعلى للأقل',
    highest_rated: 'الأعلى تقييماً',
    clear_filters: 'مسح جميع المرشحات',
    no_products_found: 'لم نجد أي منتجات',
    try_different_filters: 'جرب تغيير المرشحات أو البحث عن شيء آخر',
    
    // Product Detail
    description: 'الوصف',
    quantity: 'الكمية',
    in_stock: 'متوفر',
    add_to_cart: 'أضف للسلة',
    buy_now: 'اشتري الآن',
    related_products: 'منتجات ذات صلة',
    add_to_wishlist: 'أضف للمفضلة',
    share: 'مشاركة',
    reviews: 'التقييمات',
    specifications: 'المواصفات',
    
    // Cart
    shopping_cart: 'سلة التسوق',
    cart_empty: 'سلة التسوق فارغة',
    cart_empty_desc: 'لم تقم بإضافة أي منتجات بعد',
    continue_shopping: 'تابع التسوق',
    subtotal: 'المجموع الجزئي',
    shipping: 'الشحن',
    total: 'المجموع',
    free: 'مجاني',
    checkout: 'إتمام الطلب',
    remove: 'حذف',
    update_cart: 'تحديث السلة',
    
    // Checkout
    billing_details: 'بيانات الفاتورة',
    shipping_details: 'بيانات الشحن',
    payment_method: 'طريقة الدفع',
    place_order: 'تأكيد الطلب',
    order_summary: 'ملخص الطلب',
    credit_card: 'بطاقة ائتمان',
    address: 'العنوان',
    city: 'المدينة',
    postal_code: 'الرمز البريدي',
    country: 'الدولة',
    
    // Auth
    sign_in: 'تسجيل الدخول',
    sign_up: 'إنشاء حساب جديد',
    welcome_back: 'مرحباً بعودتك!',
    join_family: 'انضم إلى عائلة Auraa Luxury',
    first_name: 'الاسم الأول',
    last_name: 'الاسم الأخير',
    email: 'البريد الإلكتروني',
    phone: 'رقم الجوال',
    password: 'كلمة المرور',
    confirm_password: 'تأكيد كلمة المرور',
    no_account: 'ليس لديك حساب؟',
    have_account: 'لديك حساب بالفعل؟',
    create_account: 'إنشاء حساب جديد',
    forgot_password: 'نسيت كلمة المرور؟',
    
    // Profile
    my_orders: 'طلباتي',
    my_wishlist: 'المفضلة',
    account_settings: 'إعدادات الحساب',
    order_history: 'سجل الطلبات',
    save_changes: 'حفظ التغييرات',
    
    // Currency
    currency: 'العملة'
  },
  
  en: {
    // Navigation
    home: 'Home',
    products: 'Products',
    necklaces: 'Necklaces',
    earrings: 'Earrings',
    rings: 'Rings',
    bracelets: 'Bracelets',
    watches: 'Watches',
    sets: 'Sets',
    cart: 'Cart',
    profile: 'Profile',
    admin: 'Admin',
    login: 'Login / Register',
    logout: 'Logout',
    search_placeholder: 'Search for products...',
    language: 'Language',
    
    // Homepage
    welcome_message: 'Welcome to',
    hero_subtitle: 'Discover our luxury collection of elegant accessories and fine jewelry',
    shop_now: 'Shop Now',
    featured_sets: 'Featured Sets',
    free_shipping: 'Free Shipping',
    free_shipping_desc: 'Free shipping on all orders over 200 SAR',
    quality_guarantee: 'Quality Guarantee',
    quality_guarantee_desc: 'Full warranty on all our products for one year',
    support_247: '24/7 Support',
    support_247_desc: 'Customer service team available around the clock',
    shop_by_category: 'Shop by Category',
    featured_products: 'Featured Products',
    newsletter_title: 'Subscribe to Our Newsletter',
    newsletter_subtitle: 'Get the latest offers and new products',
    subscribe: 'Subscribe',
    luxury_collection: 'Luxury Collection',
    
    // Products
    all_products: 'All Products',
    filter_results: 'Filter Results',
    category: 'Category',
    all_categories: 'All Categories',
    price_range: 'Price Range',
    sort_by: 'Sort By',
    newest: 'Newest',
    price_low_high: 'Price: Low to High',
    price_high_low: 'Price: High to Low',
    highest_rated: 'Highest Rated',
    clear_filters: 'Clear All Filters',
    no_products_found: 'No Products Found',
    try_different_filters: 'Try changing the filters or search for something else',
    
    // Product Detail
    description: 'Description',
    quantity: 'Quantity',
    in_stock: 'In Stock',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    related_products: 'Related Products',
    add_to_wishlist: 'Add to Wishlist',
    share: 'Share',
    reviews: 'Reviews',
    specifications: 'Specifications',
    
    // Cart
    shopping_cart: 'Shopping Cart',
    cart_empty: 'Shopping Cart is Empty',
    cart_empty_desc: 'You have not added any products yet',
    continue_shopping: 'Continue Shopping',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    free: 'Free',
    checkout: 'Checkout',
    remove: 'Remove',
    update_cart: 'Update Cart',
    
    // Checkout
    billing_details: 'Billing Details',
    shipping_details: 'Shipping Details',
    payment_method: 'Payment Method',
    place_order: 'Place Order',
    order_summary: 'Order Summary',
    credit_card: 'Credit Card',
    address: 'Address',
    city: 'City',
    postal_code: 'Postal Code',
    country: 'Country',
    
    // Auth
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    welcome_back: 'Welcome Back!',
    join_family: 'Join the Auraa Luxury Family',
    first_name: 'First Name',
    last_name: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    password: 'Password',
    confirm_password: 'Confirm Password',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    create_account: 'Create New Account',
    forgot_password: 'Forgot Password?',
    
    // Profile
    my_orders: 'My Orders',
    my_wishlist: 'My Wishlist',
    account_settings: 'Account Settings',
    order_history: 'Order History',
    save_changes: 'Save Changes',
    
    // Currency
    currency: 'Currency'
  },
  
  fr: {
    home: 'Accueil',
    products: 'Produits',
    necklaces: 'Colliers',
    earrings: 'Boucles d\'oreilles',
    rings: 'Bagues',
    bracelets: 'Bracelets',
    watches: 'Montres',
    sets: 'Ensembles',
    cart: 'Panier',
    profile: 'Profil',
    admin: 'Administration',
    login: 'Connexion / Inscription',
    logout: 'Déconnexion',
    search_placeholder: 'Rechercher des produits...',
    language: 'Langue',
    welcome_message: 'Bienvenue chez',
    hero_subtitle: 'Découvrez notre collection de luxe d\'accessoires élégants',
    shop_now: 'Acheter maintenant',
    featured_sets: 'Ensembles en vedette',
    free_shipping: 'Livraison gratuite',
    free_shipping_desc: 'Livraison gratuite sur toutes les commandes',
    quality_guarantee: 'Garantie de qualité',
    quality_guarantee_desc: 'Garantie complète sur tous nos produits',
    support_247: 'Support 24/7',
    support_247_desc: 'Service client disponible 24h/24',
    shop_by_category: 'Acheter par catégorie',
    featured_products: 'Produits en vedette',
    all_products: 'Tous les produits',
    filter_results: 'Filtrer les résultats',
    category: 'Catégorie',
    all_categories: 'Toutes les catégories',
    price_range: 'Gamme de prix',
    sort_by: 'Trier par',
    newest: 'Plus récent',
    price_low_high: 'Prix: Bas à Élevé',
    price_high_low: 'Prix: Élevé à Bas',
    highest_rated: 'Mieux noté',
    clear_filters: 'Effacer les filtres',
    no_products_found: 'Aucun produit trouvé',
    try_different_filters: 'Essayez de changer les filtres',
    description: 'Description',
    quantity: 'Quantité',
    in_stock: 'En stock',
    add_to_cart: 'Ajouter au panier',
    buy_now: 'Acheter maintenant',
    related_products: 'Produits connexes',
    add_to_wishlist: 'Ajouter aux favoris',
    share: 'Partager',
    reviews: 'Avis',
    specifications: 'Spécifications',
    shopping_cart: 'Panier',
    cart_empty: 'Panier vide',
    cart_empty_desc: 'Vous n\'avez ajouté aucun produit',
    continue_shopping: 'Continuer les achats',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    total: 'Total',
    free: 'Gratuit',
    checkout: 'Passer la commande',
    remove: 'Supprimer',
    update_cart: 'Mettre à jour le panier',
    billing_details: 'Détails de facturation',
    shipping_details: 'Détails de livraison',
    payment_method: 'Mode de paiement',
    place_order: 'Passer la commande',
    order_summary: 'Résumé de la commande',
    credit_card: 'Carte de crédit',
    address: 'Adresse',
    city: 'Ville',
    postal_code: 'Code postal',
    country: 'Pays',
    sign_in: 'Se connecter',
    sign_up: 'S\'inscrire',
    welcome_back: 'Bon retour!',
    join_family: 'Rejoignez la famille Auraa Luxury',
    first_name: 'Prénom',
    last_name: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    password: 'Mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    no_account: 'Pas de compte?',
    have_account: 'Vous avez déjà un compte?',
    create_account: 'Créer un compte',
    forgot_password: 'Mot de passe oublié?',
    my_orders: 'Mes commandes',
    my_wishlist: 'Mes favoris',
    account_settings: 'Paramètres du compte',
    order_history: 'Historique des commandes',
    save_changes: 'Sauvegarder',
    currency: 'Devise',
    newsletter_title: 'Abonnez-vous à notre newsletter',
    newsletter_subtitle: 'Recevez les dernières offres',
    subscribe: 'S\'abonner',
    luxury_collection: 'Collection de luxe'
  },
  
  es: {
    home: 'Inicio',
    products: 'Productos',
    necklaces: 'Collares',
    earrings: 'Pendientes',
    rings: 'Anillos',
    bracelets: 'Pulseras',
    watches: 'Relojes',
    sets: 'Conjuntos',
    cart: 'Carrito',
    profile: 'Perfil',
    admin: 'Administración',
    login: 'Iniciar sesión / Registrarse',
    logout: 'Cerrar sesión',
    search_placeholder: 'Buscar productos...',
    language: 'Idioma',
    welcome_message: 'Bienvenido a',
    hero_subtitle: 'Descubre nuestra colección de lujo de accesorios elegantes',
    shop_now: 'Comprar ahora',
    featured_sets: 'Conjuntos destacados',
    free_shipping: 'Envío gratis',
    free_shipping_desc: 'Envío gratis en todos los pedidos',
    quality_guarantee: 'Garantía de calidad',
    quality_guarantee_desc: 'Garantía completa en todos nuestros productos',
    support_247: 'Soporte 24/7',
    support_247_desc: 'Servicio al cliente disponible las 24 horas',
    shop_by_category: 'Comprar por categoría',
    featured_products: 'Productos destacados',
    all_products: 'Todos los productos',
    filter_results: 'Filtrar resultados',
    category: 'Categoría',
    all_categories: 'Todas las categorías',
    price_range: 'Rango de precio',
    sort_by: 'Ordenar por',
    newest: 'Más nuevo',
    price_low_high: 'Precio: Bajo a Alto',
    price_high_low: 'Precio: Alto a Bajo',
    highest_rated: 'Mejor valorado',
    clear_filters: 'Limpiar filtros',
    no_products_found: 'No se encontraron productos',
    try_different_filters: 'Intenta cambiar los filtros',
    description: 'Descripción',
    quantity: 'Cantidad',
    in_stock: 'En stock',
    add_to_cart: 'Añadir al carrito',
    buy_now: 'Comprar ahora',
    related_products: 'Productos relacionados',
    add_to_wishlist: 'Añadir a favoritos',
    share: 'Compartir',
    reviews: 'Reseñas',
    specifications: 'Especificaciones',
    shopping_cart: 'Carrito de compras',
    cart_empty: 'Carrito vacío',
    cart_empty_desc: 'No has añadido ningún producto',
    continue_shopping: 'Continuar comprando',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    total: 'Total',
    free: 'Gratis',
    checkout: 'Finalizar compra',
    remove: 'Eliminar',
    update_cart: 'Actualizar carrito',
    billing_details: 'Detalles de facturación',
    shipping_details: 'Detalles de envío',
    payment_method: 'Método de pago',
    place_order: 'Realizar pedido',
    order_summary: 'Resumen del pedido',
    credit_card: 'Tarjeta de crédito',
    address: 'Dirección',
    city: 'Ciudad',
    postal_code: 'Código postal',
    country: 'País',
    sign_in: 'Iniciar sesión',
    sign_up: 'Registrarse',
    welcome_back: '¡Bienvenido de nuevo!',
    join_family: 'Únete a la familia Auraa Luxury',
    first_name: 'Nombre',
    last_name: 'Apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono',
    password: 'Contraseña',
    confirm_password: 'Confirmar contraseña',
    no_account: '¿No tienes cuenta?',
    have_account: '¿Ya tienes una cuenta?',
    create_account: 'Crear cuenta',
    forgot_password: '¿Olvidaste tu contraseña?',
    my_orders: 'Mis pedidos',
    my_wishlist: 'Mis favoritos',
    account_settings: 'Configuración de cuenta',
    order_history: 'Historial de pedidos',
    save_changes: 'Guardar cambios',
    currency: 'Moneda',
    newsletter_title: 'Suscríbete a nuestro boletín',
    newsletter_subtitle: 'Recibe las últimas ofertas',
    subscribe: 'Suscribirse',
    luxury_collection: 'Colección de lujo'
  },
  
  de: {
    home: 'Startseite',
    products: 'Produkte',
    necklaces: 'Halsketten',
    earrings: 'Ohrringe',
    rings: 'Ringe',
    bracelets: 'Armbänder',
    watches: 'Uhren',
    sets: 'Sets',
    cart: 'Warenkorb',
    profile: 'Profil',
    admin: 'Verwaltung',
    login: 'Anmelden / Registrieren',
    logout: 'Abmelden',
    search_placeholder: 'Produkte suchen...',
    language: 'Sprache',
    welcome_message: 'Willkommen bei',
    hero_subtitle: 'Entdecken Sie unsere Luxuskollektion eleganter Accessoires',
    shop_now: 'Jetzt einkaufen',
    featured_sets: 'Ausgewählte Sets',
    free_shipping: 'Kostenloser Versand',
    free_shipping_desc: 'Kostenloser Versand bei allen Bestellungen',
    quality_guarantee: 'Qualitätsgarantie',
    quality_guarantee_desc: 'Vollständige Garantie auf alle unsere Produkte',
    support_247: '24/7 Support',
    support_247_desc: 'Kundenservice rund um die Uhr verfügbar',
    shop_by_category: 'Nach Kategorie einkaufen',
    featured_products: 'Ausgewählte Produkte',
    all_products: 'Alle Produkte',
    filter_results: 'Ergebnisse filtern',
    category: 'Kategorie',
    all_categories: 'Alle Kategorien',
    price_range: 'Preisspanne',
    sort_by: 'Sortieren nach',
    newest: 'Neueste',
    price_low_high: 'Preis: Niedrig bis Hoch',
    price_high_low: 'Preis: Hoch bis Niedrig',
    highest_rated: 'Bestbewertet',
    clear_filters: 'Filter löschen',
    no_products_found: 'Keine Produkte gefunden',
    try_different_filters: 'Versuchen Sie, die Filter zu ändern',
    description: 'Beschreibung',
    quantity: 'Menge',
    in_stock: 'Auf Lager',
    add_to_cart: 'In den Warenkorb',
    buy_now: 'Jetzt kaufen',
    related_products: 'Verwandte Produkte',
    add_to_wishlist: 'Zur Wunschliste',
    share: 'Teilen',
    reviews: 'Bewertungen',
    specifications: 'Spezifikationen',
    shopping_cart: 'Warenkorb',
    cart_empty: 'Warenkorb ist leer',
    cart_empty_desc: 'Sie haben noch keine Produkte hinzugefügt',
    continue_shopping: 'Weiter einkaufen',
    subtotal: 'Zwischensumme',
    shipping: 'Versand',
    total: 'Gesamt',
    free: 'Kostenlos',
    checkout: 'Zur Kasse',
    remove: 'Entfernen',
    update_cart: 'Warenkorb aktualisieren',
    billing_details: 'Rechnungsdetails',
    shipping_details: 'Versanddetails',
    payment_method: 'Zahlungsmethode',
    place_order: 'Bestellung aufgeben',
    order_summary: 'Bestellübersicht',
    credit_card: 'Kreditkarte',
    address: 'Adresse',
    city: 'Stadt',
    postal_code: 'Postleitzahl',
    country: 'Land',
    sign_in: 'Anmelden',
    sign_up: 'Registrieren',
    welcome_back: 'Willkommen zurück!',
    join_family: 'Werden Sie Teil der Auraa Luxury Familie',
    first_name: 'Vorname',
    last_name: 'Nachname',
    email: 'E-Mail',
    phone: 'Telefon',
    password: 'Passwort',
    confirm_password: 'Passwort bestätigen',
    no_account: 'Kein Konto?',
    have_account: 'Haben Sie bereits ein Konto?',
    create_account: 'Konto erstellen',
    forgot_password: 'Passwort vergessen?',
    my_orders: 'Meine Bestellungen',
    my_wishlist: 'Meine Wunschliste',
    account_settings: 'Kontoeinstellungen',
    order_history: 'Bestellverlauf',
    save_changes: 'Änderungen speichern',
    currency: 'Währung',
    newsletter_title: 'Abonnieren Sie unseren Newsletter',
    newsletter_subtitle: 'Erhalten Sie die neuesten Angebote',
    subscribe: 'Abonnieren',
    luxury_collection: 'Luxuskollektion'
  },
  
  it: {
    home: 'Home',
    products: 'Prodotti',
    necklaces: 'Collane',
    earrings: 'Orecchini',
    rings: 'Anelli',
    bracelets: 'Bracciali',
    watches: 'Orologi',
    sets: 'Set',
    cart: 'Carrello',
    profile: 'Profilo',
    admin: 'Amministrazione',
    login: 'Accedi / Registrati',
    logout: 'Esci',
    search_placeholder: 'Cerca prodotti...',
    language: 'Lingua',
    welcome_message: 'Benvenuto a',
    hero_subtitle: 'Scopri la nostra collezione di lusso di accessori eleganti',
    shop_now: 'Acquista ora',
    featured_sets: 'Set in evidenza',
    free_shipping: 'Spedizione gratuita',
    free_shipping_desc: 'Spedizione gratuita su tutti gli ordini',
    quality_guarantee: 'Garanzia di qualità',
    quality_guarantee_desc: 'Garanzia completa su tutti i nostri prodotti',
    support_247: 'Supporto 24/7',
    support_247_desc: 'Servizio clienti disponibile 24 ore su 24',
    shop_by_category: 'Acquista per categoria',
    featured_products: 'Prodotti in evidenza',
    all_products: 'Tutti i prodotti',
    filter_results: 'Filtra risultati',
    category: 'Categoria',
    all_categories: 'Tutte le categorie',
    price_range: 'Fascia di prezzo',
    sort_by: 'Ordina per',
    newest: 'Più recente',
    price_low_high: 'Prezzo: Dal più basso',
    price_high_low: 'Prezzo: Dal più alto',
    highest_rated: 'Più votato',
    clear_filters: 'Cancella filtri',
    no_products_found: 'Nessun prodotto trovato',
    try_different_filters: 'Prova a cambiare i filtri',
    description: 'Descrizione',
    quantity: 'Quantità',
    in_stock: 'Disponibile',
    add_to_cart: 'Aggiungi al carrello',
    buy_now: 'Acquista ora',
    related_products: 'Prodotti correlati',
    add_to_wishlist: 'Aggiungi ai preferiti',
    share: 'Condividi',
    reviews: 'Recensioni',
    specifications: 'Specifiche',
    shopping_cart: 'Carrello',
    cart_empty: 'Carrello vuoto',
    cart_empty_desc: 'Non hai aggiunto alcun prodotto',
    continue_shopping: 'Continua lo shopping',
    subtotal: 'Subtotale',
    shipping: 'Spedizione',
    total: 'Totale',
    free: 'Gratuito',
    checkout: 'Checkout',
    remove: 'Rimuovi',
    update_cart: 'Aggiorna carrello',
    billing_details: 'Dettagli di fatturazione',
    shipping_details: 'Dettagli di spedizione',
    payment_method: 'Metodo di pagamento',
    place_order: 'Effettua ordine',
    order_summary: 'Riepilogo ordine',
    credit_card: 'Carta di credito',
    address: 'Indirizzo',
    city: 'Città',
    postal_code: 'Codice postale',
    country: 'Paese',
    sign_in: 'Accedi',
    sign_up: 'Registrati',
    welcome_back: 'Bentornato!',
    join_family: 'Unisciti alla famiglia Auraa Luxury',
    first_name: 'Nome',
    last_name: 'Cognome',
    email: 'Email',
    phone: 'Telefono',
    password: 'Password',
    confirm_password: 'Conferma password',
    no_account: 'Non hai un account?',
    have_account: 'Hai già un account?',
    create_account: 'Crea account',
    forgot_password: 'Password dimenticata?',
    my_orders: 'I miei ordini',
    my_wishlist: 'I miei preferiti',
    account_settings: 'Impostazioni account',
    order_history: 'Cronologia ordini',
    save_changes: 'Salva modifiche',
    currency: 'Valuta',
    newsletter_title: 'Iscriviti alla nostra newsletter',
    newsletter_subtitle: 'Ricevi le ultime offerte',
    subscribe: 'Iscriviti',
    luxury_collection: 'Collezione di lusso'
  },
  
  tr: {
    home: 'Ana Sayfa',
    products: 'Ürünler',
    necklaces: 'Kolyeler',
    earrings: 'Küpeler',
    rings: 'Yüzükler',
    bracelets: 'Bilezikler',
    watches: 'Saatler',
    sets: 'Setler',
    cart: 'Sepet',
    profile: 'Profil',
    admin: 'Yönetim',
    login: 'Giriş / Kayıt',
    logout: 'Çıkış',
    search_placeholder: 'Ürün ara...',
    language: 'Dil',
    welcome_message: 'Hoş geldiniz',
    hero_subtitle: 'Lüks aksesuarlar koleksiyonumuzu keşfedin',
    shop_now: 'Hemen Alışveriş',
    featured_sets: 'Öne Çıkan Setler',
    free_shipping: 'Ücretsiz Kargo',
    free_shipping_desc: 'Tüm siparişlerde ücretsiz kargo',
    quality_guarantee: 'Kalite Garantisi',
    quality_guarantee_desc: 'Tüm ürünlerimizde tam garanti',
    support_247: '7/24 Destek',
    support_247_desc: 'Müşteri hizmetleri 7/24 hizmetinizde',
    shop_by_category: 'Kategoriye Göre Alışveriş',
    featured_products: 'Öne Çıkan Ürünler',
    all_products: 'Tüm Ürünler',
    filter_results: 'Sonuçları Filtrele',
    category: 'Kategori',
    all_categories: 'Tüm Kategoriler',
    price_range: 'Fiyat Aralığı',
    sort_by: 'Sırala',
    newest: 'En Yeni',
    price_low_high: 'Fiyat: Düşükten Yükseğe',
    price_high_low: 'Fiyat: Yüksekten Düşüğe',
    highest_rated: 'En Yüksek Puan',
    clear_filters: 'Filtreleri Temizle',
    no_products_found: 'Ürün Bulunamadı',
    try_different_filters: 'Farklı filtreler deneyin',
    description: 'Açıklama',
    quantity: 'Miktar',
    in_stock: 'Stokta',
    add_to_cart: 'Sepete Ekle',
    buy_now: 'Hemen Al',
    related_products: 'İlgili Ürünler',
    add_to_wishlist: 'Favorilere Ekle',
    share: 'Paylaş',
    reviews: 'Yorumlar',
    specifications: 'Özellikler',
    shopping_cart: 'Alışveriş Sepeti',
    cart_empty: 'Sepet Boş',
    cart_empty_desc: 'Henüz ürün eklemediniz',
    continue_shopping: 'Alışverişe Devam',
    subtotal: 'Ara Toplam',
    shipping: 'Kargo',
    total: 'Toplam',
    free: 'Ücretsiz',
    checkout: 'Ödeme',
    remove: 'Kaldır',
    update_cart: 'Sepeti Güncelle',
    billing_details: 'Fatura Bilgileri',
    shipping_details: 'Teslimat Bilgileri',
    payment_method: 'Ödeme Yöntemi',
    place_order: 'Sipariş Ver',
    order_summary: 'Sipariş Özeti',
    credit_card: 'Kredi Kartı',
    address: 'Adres',
    city: 'Şehir',
    postal_code: 'Posta Kodu',
    country: 'Ülke',
    sign_in: 'Giriş Yap',
    sign_up: 'Kayıt Ol',
    welcome_back: 'Tekrar Hoş Geldiniz!',
    join_family: 'Auraa Luxury Ailesine Katılın',
    first_name: 'Ad',
    last_name: 'Soyad',
    email: 'E-posta',
    phone: 'Telefon',
    password: 'Şifre',
    confirm_password: 'Şifreyi Onayla',
    no_account: 'Hesabınız yok mu?',
    have_account: 'Zaten hesabınız var mı?',
    create_account: 'Hesap Oluştur',
    forgot_password: 'Şifremi Unuttum?',
    my_orders: 'Siparişlerim',
    my_wishlist: 'Favorilerim',
    account_settings: 'Hesap Ayarları',
    order_history: 'Sipariş Geçmişi',
    save_changes: 'Değişiklikleri Kaydet',
    currency: 'Para Birimi',
    newsletter_title: 'Bültenimize Abone Olun',
    newsletter_subtitle: 'En son teklifleri alın',
    subscribe: 'Abone Ol',
    luxury_collection: 'Lüks Koleksiyon'
  },
  
  ur: {
    home: 'ہوم',
    products: 'مصنوعات',
    necklaces: 'ہار',
    earrings: 'بالیاں',
    rings: 'انگوٹھیاں',
    bracelets: 'کنگن',
    watches: 'گھڑیاں',
    sets: 'سیٹ',
    cart: 'ٹوکری',
    profile: 'پروفائل',
    admin: 'منتظم',
    login: 'لاگ ان / رجسٹر',
    logout: 'لاگ آؤٹ',
    search_placeholder: 'مصنوعات تلاش کریں...',
    language: 'زبان',
    welcome_message: 'خوش آمدید',
    hero_subtitle: 'ہمارے لگژری زیورات کا مجموعہ دریافت کریں',
    shop_now: 'ابھی خریدیں',
    featured_sets: 'خصوصی سیٹ',
    free_shipping: 'مفت ترسیل',
    free_shipping_desc: 'تمام آرڈرز پر مفت ڈیلیوری',
    quality_guarantee: 'معیار کی ضمانت',
    quality_guarantee_desc: 'ہماری تمام مصنوعات پر مکمل وارنٹی',
    support_247: '24/7 سپورٹ',
    support_247_desc: 'کسٹمر سروس 24 گھنٹے دستیاب',
    shop_by_category: 'زمرہ کے مطابق خریداری',
    featured_products: 'نمایاں مصنوعات',
    all_products: 'تمام مصنوعات',
    filter_results: 'نتائج فلٹر کریں',
    category: 'زمرہ',
    all_categories: 'تمام زمرے',
    price_range: 'قیمت کی حد',
    sort_by: 'ترتیب دیں',
    newest: 'تازہ ترین',
    price_low_high: 'قیمت: کم سے زیادہ',
    price_high_low: 'قیمت: زیادہ سے کم',
    highest_rated: 'بہترین درجہ بند',
    clear_filters: 'فلٹرز صاف کریں',
    no_products_found: 'کوئی مصنوعات نہیں ملیں',
    try_different_filters: 'مختلف فلٹرز آزمائیں',
    description: 'تفصیل',
    quantity: 'مقدار',
    in_stock: 'اسٹاک میں',
    add_to_cart: 'ٹوکری میں شامل کریں',
    buy_now: 'ابھی خریدیں',
    related_products: 'متعلقہ مصنوعات',
    add_to_wishlist: 'پسندیدہ میں شامل کریں',
    share: 'شیئر کریں',
    reviews: 'جائزے',
    specifications: 'تفصیلات',
    shopping_cart: 'خریداری کی ٹوکری',
    cart_empty: 'ٹوکری خالی ہے',
    cart_empty_desc: 'آپ نے ابھی تک کوئی مصنوعات شامل نہیں کیں',
    continue_shopping: 'خریداری جاری رکھیں',
    subtotal: 'ذیلی کل',
    shipping: 'ترسیل',
    total: 'کل',
    free: 'مفت',
    checkout: 'چیک آؤٹ',
    remove: 'ہٹائیں',
    update_cart: 'ٹوکری اپ ڈیٹ کریں',
    billing_details: 'بلنگ کی تفصیلات',
    shipping_details: 'ترسیل کی تفصیلات',
    payment_method: 'ادائیگی کا طریقہ',
    place_order: 'آرڈر دیں',
    order_summary: 'آرڈر کا خلاصہ',
    credit_card: 'کریڈٹ کارڈ',
    address: 'پتہ',
    city: 'شہر',
    postal_code: 'پوسٹل کوڈ',
    country: 'ملک',
    sign_in: 'لاگ ان',
    sign_up: 'سائن اپ',
    welcome_back: 'واپسی پر خوش آمدید!',
    join_family: 'Auraa Luxury خاندان میں شامل ہوں',
    first_name: 'پہلا نام',
    last_name: 'آخری نام',
    email: 'ای میل',
    phone: 'فون',
    password: 'پاس ورڈ',
    confirm_password: 'پاس ورڈ کی تصدیق کریں',
    no_account: 'اکاؤنٹ نہیں ہے؟',
    have_account: 'پہلے سے اکاؤنٹ ہے؟',
    create_account: 'اکاؤنٹ بنائیں',
    forgot_password: 'پاس ورڈ بھول گئے؟',
    my_orders: 'میرے آرڈرز',
    my_wishlist: 'میری پسندیدہ',
    account_settings: 'اکاؤنٹ کی ترتیبات',
    order_history: 'آرڈر کی تاریخ',
    save_changes: 'تبدیلیاں محفوظ کریں',
    currency: 'کرنسی',
    newsletter_title: 'ہمارے نیوز لیٹر کی رکنیت',
    newsletter_subtitle: 'تازہ ترین پیشکشیں حاصل کریں',
    subscribe: 'سبسکرائب کریں',
    luxury_collection: 'لگژری کلیکشن'
  },
  
  hi: {
    home: 'होम',
    products: 'उत्पाद',
    necklaces: 'हार',
    earrings: 'झुमके',
    rings: 'अंगूठियां',
    bracelets: 'कंगन',
    watches: 'घड़ियां',
    sets: 'सेट',
    cart: 'कार्ट',
    profile: 'प्रोफाइल',
    admin: 'व्यवस्थापक',
    login: 'लॉगिन / रजिस्टर',
    logout: 'लॉगआउट',
    search_placeholder: 'उत्पाद खोजें...',
    language: 'भाषा',
    welcome_message: 'स्वागत है',
    hero_subtitle: 'हमारे लक्जरी गहनों का संग्रह देखें',
    shop_now: 'अभी खरीदें',
    featured_sets: 'विशेष सेट',
    free_shipping: 'मुफ्त शिपिंग',
    free_shipping_desc: 'सभी ऑर्डर पर मुफ्त डिलीवरी',
    quality_guarantee: 'गुणवत्ता की गारंटी',
    quality_guarantee_desc: 'हमारे सभी उत्पादों पर पूर्ण वारंटी',
    support_247: '24/7 सपोर्ट',
    support_247_desc: 'ग्राहक सेवा 24 घंटे उपलब्ध',
    shop_by_category: 'श्रेणी के अनुसार खरीदें',
    featured_products: 'विशेष उत्पाद',
    all_products: 'सभी उत्पाद',
    filter_results: 'परिणाम फ़िल्टर करें',
    category: 'श्रेणी',
    all_categories: 'सभी श्रेणियां',
    price_range: 'मूल्य सीमा',
    sort_by: 'क्रमबद्ध करें',
    newest: 'नवीनतम',
    price_low_high: 'मूल्य: कम से अधिक',
    price_high_low: 'मूल्य: अधिक से कम',
    highest_rated: 'सर्वोच्च रेटेड',
    clear_filters: 'फ़िल्टर साफ़ करें',
    no_products_found: 'कोई उत्पाद नहीं मिला',
    try_different_filters: 'विभिन्न फ़िल्टर आज़माएं',
    description: 'विवरण',
    quantity: 'मात्रा',
    in_stock: 'स्टॉक में',
    add_to_cart: 'कार्ट में जोड़ें',
    buy_now: 'अभी खरीदें',
    related_products: 'संबंधित उत्पाद',
    add_to_wishlist: 'पसंदीदा में जोड़ें',
    share: 'शेयर करें',
    reviews: 'समीक्षाएं',
    specifications: 'विनिर्देश',
    shopping_cart: 'शॉपिंग कार्ट',
    cart_empty: 'कार्ट खाली है',
    cart_empty_desc: 'आपने अभी तक कोई उत्पाद नहीं जोड़ा',
    continue_shopping: 'खरीदारी जारी रखें',
    subtotal: 'उप-योग',
    shipping: 'शिपिंग',
    total: 'कुल',
    free: 'मुफ्त',
    checkout: 'चेकआउट',
    remove: 'हटाएं',
    update_cart: 'कार्ट अपडेट करें',
    billing_details: 'बिलिंग विवरण',
    shipping_details: 'शिपिंग विवरण',
    payment_method: 'भुगतान विधि',
    place_order: 'ऑर्डर दें',
    order_summary: 'ऑर्डर सारांश',
    credit_card: 'क्रेडिट कार्ड',
    address: 'पता',
    city: 'शहर',
    postal_code: 'पोस्टल कोड',
    country: 'देश',
    sign_in: 'साइन इन',
    sign_up: 'साइन अप',
    welcome_back: 'वापसी पर स्वागत है!',
    join_family: 'Auraa Luxury परिवार में शामिल हों',
    first_name: 'पहला नाम',
    last_name: 'अंतिम नाम',
    email: 'ईमेल',
    phone: 'फोन',
    password: 'पासवर्ड',
    confirm_password: 'पासवर्ड की पुष्टि करें',
    no_account: 'खाता नहीं है?',
    have_account: 'पहले से खाता है?',
    create_account: 'खाता बनाएं',
    forgot_password: 'पासवर्ड भूल गए?',
    my_orders: 'मेरे ऑर्डर',
    my_wishlist: 'मेरी पसंदीदा',
    account_settings: 'खाता सेटिंग',
    order_history: 'ऑर्डर इतिहास',
    save_changes: 'परिवर्तन सहेजें',
    currency: 'मुद्रा',
    newsletter_title: 'हमारे न्यूज़लेटर की सदस्यता लें',
    newsletter_subtitle: 'नवीनतम ऑफ़र प्राप्त करें',
    subscribe: 'सदस्यता लें',
    luxury_collection: 'लक्जरी कलेक्शन'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'ar';
  });
  
  const [currency, setCurrency] = useState(() => {
    return localStorage.getItem('currency') || 'SAR';
  });

  const [exchangeRates, setExchangeRates] = useState({});

  // Fetch live exchange rates from API
  useEffect(() => {
    const fetchExchangeRates = async () => {
      try {
        // Using exchangerate-api.com (free tier - 1500 requests/month)
        const response = await fetch('https://api.exchangerate-api.com/v4/latest/USD');
        const data = await response.json();
        setExchangeRates(data.rates);
      } catch (error) {
        console.error('Failed to fetch exchange rates:', error);
        // Fallback to static rates
        setExchangeRates({
          USD: 1,
          SAR: 3.75,
          AED: 3.67,
          QAR: 3.64,
          KWD: 0.31,
          BHD: 0.38,
          OMR: 0.38
        });
      }
    };

    fetchExchangeRates();
    // Refresh rates every hour
    const interval = setInterval(fetchExchangeRates, 3600000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    const dir = LANGUAGES[language]?.dir || 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    localStorage.setItem('currency', currency);
  }, [currency]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const formatPrice = (priceInUSD) => {
    if (!priceInUSD || !exchangeRates[currency]) return '0';
    
    const currencyInfo = CURRENCIES[currency];
    const convertedPrice = priceInUSD * exchangeRates[currency];
    const formattedPrice = convertedPrice.toFixed(currencyInfo.decimals);
    
    return `${formattedPrice} ${currencyInfo.symbol}`;
  };

  const convertToUSD = (priceInCurrency) => {
    if (!priceInCurrency || !exchangeRates[currency]) return 0;
    return priceInCurrency / exchangeRates[currency];
  };

  const switchLanguage = (newLanguage) => {
    if (LANGUAGES[newLanguage]) {
      setLanguage(newLanguage);
    }
  };

  const switchCurrency = (newCurrency) => {
    if (CURRENCIES[newCurrency]) {
      setCurrency(newCurrency);
    }
  };

  const value = {
    language,
    currency,
    t,
    formatPrice,
    convertToUSD,
    switchLanguage,
    switchCurrency,
    languages: LANGUAGES,
    currencies: CURRENCIES,
    exchangeRates,
    isRTL: LANGUAGES[language]?.dir === 'rtl'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};