name: Deploy Backend to Render (DISABLED - Using Kubernetes)

# This workflow is disabled as we deploy via Kubernetes, not Render
# Keep for reference only

on:
  workflow_dispatch: {}  # Manual trigger only
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: false  # Disabled - using Kubernetes deployment
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          echo "⚠️ This workflow is disabled"
          echo "Backend is deployed via Kubernetes (supervisor)"
          echo "No action needed"