name: Deploy Backend to Render

on:
  push:
    branches: [ '*' ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -n "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "🚀 Triggering Render deployment..."
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
            echo "✅ Deploy hook triggered successfully"
          else
            echo "⚠️  RENDER_DEPLOY_HOOK not set - skipping deploy"
          fi