name: Deploy via Vercel Hook (Backup Method)

on:
  workflow_dispatch: {}
  # Uncomment below to enable auto-deploy on push
  # push:
  #   branches: [ "main" ]

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Deploy Hook Secret
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            echo "❌ VERCEL_DEPLOY_HOOK is not set in GitHub Secrets"
            echo "Please add it in: Settings → Secrets and variables → Actions"
            exit 1
          fi
          echo "✅ VERCEL_DEPLOY_HOOK found"

      - name: Trigger Vercel Deployment
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -eq 200 ] || [ "$http_code" -eq 201 ]; then
            echo "✅ Deployment triggered successfully!"
          else
            echo "❌ Deployment trigger failed with status: $http_code"
            exit 1
          fi

      - name: Deployment Information
        if: success()
        run: |
          echo "✅ Vercel deployment has been triggered via Deploy Hook"
          echo "🌐 Check Vercel Dashboard for deployment status"
          echo "📝 Note: This method uses Vercel's built-in build process"
