name: Deploy Backend to Render (DISABLED - Using Kubernetes)

# This workflow is disabled as we deploy via Kubernetes, not Render
# Keep for reference only

on:
  push:
    branches: [ main, feat/admin-suite-complete ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: false  # Disabled - using Kubernetes deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "❌ RENDER_DEPLOY_HOOK secret not found!"
            echo "Please add RENDER_DEPLOY_HOOK to repository secrets."
            exit 1
          fi
          echo "✅ RENDER_DEPLOY_HOOK found"

      - name: Trigger Render Deploy Hook
        run: |
          echo "🚀 Triggering Render deployment..."
          
          # Make the API call with error checking
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}")
          
          if [ $HTTP_STATUS -eq 200 ] || [ $HTTP_STATUS -eq 201 ]; then
            echo "✅ Deploy hook triggered successfully (HTTP $HTTP_STATUS)"
            echo "🔄 Render deployment started"
          else
            echo "❌ Deploy hook failed with HTTP status: $HTTP_STATUS"
            exit 1
          fi

      - name: Deployment Success Notification
        if: success()
        run: |
          echo "🎉 Backend deployment hook triggered successfully!"
          echo "🔗 Check deployment status at: https://dashboard.render.com"

      - name: Deployment Failure Notification
        if: failure()
        run: |
          echo "❌ Backend deployment failed!"
          echo "🔍 Please check:"
          echo "   - RENDER_DEPLOY_HOOK secret is correct"
          echo "   - Render service is properly configured"
