name: Build and Release Production Bundle

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure deploy scripts are executable
        run: |
          chmod +x deploy.sh || true
          chmod +x cleanup.sh || true

      - name: Create production bundle (.zip)
        run: |
          zip -r AuraaLuxury_Production_Bundle.zip backend frontend deploy.sh cleanup.sh ONE_CLICK_README.md

      - name: Compute SHA-256
        run: |
          sha256sum AuraaLuxury_Production_Bundle.zip | tee SHA256SUMS.txt

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AuraaLuxury_Production_Bundle.zip
            SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}